---
title: "Homework 4"
author: "Ravi Patel"
date: "February 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(datasets)
library(ggplot2)
```

Question 1
```{r}
weight0 <- ChickWeight %>%
  group_by(Chick) %>%
  summarize(
    freq = n(),
    weight = mean(weight, na.rm = TRUE),
    # Resulting in NA
    sd = sd(weight, na.rm = TRUE) 
  ) 
weight0

```

Question 2
```{r}
# A vector of the chick numbers that have 12 measurements
g <- ChickWeight %>%
  group_by(Chick) %>%
  summarize(n = n()) %>%
  filter(n == 12) %>%
  select(-n)

Chicks <- ChickWeight

Chicks$Chick <- as.numeric(Chicks$Chick)
g$Chick <- as.numeric(g$Chick)

complete <- filter(Chicks, Chicks$Chick %in% g$Chick)
complete$Chick <- as.factor(complete$Chick)
head(complete, 3)
```
Question 3:
```{r}
complete <- ChickWeight %>%
  group_by(Chick) %>%
  mutate(zerow = weight[Time == 0]) %>%
  mutate(weightgain = weight - zerow) %>%
  select(-zerow) 

head(complete, 3)
```

Question 4:
```{r}
ggplot(complete, aes(x= Diet, y = weight)) + geom_boxplot()
```

Question 5:
```{r}
large <- complete %>%
  filter(weightgain == max(weightgain))

largestGain <- max(large$weightgain)
largestGain

smallestGain <- min(large$weightgain)
smallestGain

ggplot(large, aes(x = Chick, y = weightgain, colour = Diet)) + geom_point()
```

